### ISSUE TITLE
If segments in MailChimp are deleted, there is no way to regenerate them

### ISSUE THREAD

**Issue by brashrebel** [realbigplugins/learndash-mailchimp#49]
Maybe we should check to see if they exist whenever a different list is selected. That way to check again one could save the settings with a different list and then switch back at which point the segment creation button would reappear.

**Comment by objectsweb** [comment]
@brashrebel  this is out of scope. it can be moved to milestone 1.1

Thanks

**Comment by d4mation** [comment]
Re-milestoned this for v1.1, but this may already exist as part of v1.0?

> Maybe we should check to see if they exist whenever a different list is selected. That way to check again one could save the settings with a different list and then switch back at which point the segment creation button would reappear.

If a different List is selected on the Settings screen and then saved, it then checks if a specific Post Meta Key exists or not in Courses. If it doesn't, it reports that the Segments for that List have not been created and gives you the opportunity to create them for each Course that is missing one.

> If segments in *MailChimp* are deleted, there is no way to regenerate them

This is where it gets iffy. The code doesn't check to see if Segments attached to a Course have been deleted from the MailChimp dashboard. So if this is what you meant, this does not exist in v1.0.

**Comment by brashrebel** [comment]
That is what I meant. If you take action within MailChimp it causes these kinds of issues.

**Comment by d4mation** [comment]
I figured based on the title, but the content of the Issue made me think otherwise.

This should be possible. Since the Segment ID is stored in Post Meta the MailChimp API class could reach out to check if the Segment ID still exists or not and if it doesn't set a flag saying that it needs regenerated.

It would be a matter of choosing when to do this check though. At the same time as checking for Courses without Segments saved to their Post Meta? When viewing the Edit screen for that Course? On a schedule so that every page load within the Admin doesn't hit the API for each Course?

I do agree with @objectsweb here that this is a bit edge-case and without it the plugin is still at MVP status, but this would be useful to have.

**Comment by d4mation** [comment]
I ended up implementing this a week or so ago. Closing

**Comment by d4mation** [comment]
The way it is handled is by deleting the Segment if it exists, then deleting the stored Post Meta. So it does not periodically check, but the option is there.
